################################################################
#
# Pipeline pipeline_splicing.py configuration file
#
################################################################

## general options


# Project name
projectname: CGATProject

# Copyright statement
copyright: CGAT (2010-2016)

# The short X.Y version.
version: 0.1

# The full version, including alpha/beta/rc tags.
release: 0.1

# Genome, e.g. hg38
genome: ''

# Directory containing genome files
genome_dir: ''

#should permutation testing be carried out on design tables
# 0 > no, 1 > yes, currently rMATS only
# if yes, please specify number of permutations (100 good start)
permute: 0
permutations: ''


################################################################
#
# Location of annotations database
#
################################################################
annotations:
    database: ''

    # directory with annotation information
    dir: ''


################################################################
#
# MATS options
#
################################################################
MATS:
    # Cutoff splicing difference
    # The cutoff used in the null hypothesis test for differential splicing. 
    # The default is 0.0001 for 0.01% difference. Valid: 0 <= cutoff < 1
    cutoff: ''

    # PSI threshold
    # This allows for setting a fixed minimum PSI change (e.g. 0.1) for filtering
    # results. This can be used with a more lenient cstat, to increase the number
    # of results. The threshold is not hypothesis-tested
    psi: ''

    # Coverage threshold
    # This allows for setting a fixed minimum number of reads that support this
    # alternative splicing 
    coverage: ''

    # Strandednes
    # fr-firststrand, fr-secondstrand or fr-unstranded
    libtype: ''

    # FDR
    # FDR threshold for plotting of results using sashimiplot
    # only results below the threshold will be plotted
    fdr: ''

    # Number of plots
    # Maximum number of plots for sashimiplot
    # only the top n will be plotted
    plotmax: 20



################################################################
#
# DEXSeq options
#
 ################################################################
DEXSeq:

    # Strand specific library prep
    # Options are:
    # yes
    # no
    # reverse
    strandedness: ''


    # model to pass as DEXSeq design
    # for each experiment.design.tsv you need to define a model and
    # contrast and refgroup

    # e.g if you have two experiments (1.design.tsv & 2.design.tsv)
    # model_1=~group
    # contrast_1=group
    # refgroup_1=Brain1
    # model_2=~group+condition
    # contrast_2=condition
    # refgroup_2=treated

    # model needs to cotain the term exon
    # e.g. ~sample+exon+group:exon
    model_1: ''
    model_2: ''

    # contrast to return during post-hoc pairwise tests
    # e.g. group
    contrast_1: ''
    contrast_2: ''

    # reference level for contrast , e.g WT
    refgroup_1: ''
    refgroup_2: ''


    ################################################################
    #
    # IRFinder options
    #
    ################################################################
IRFinder:

    # parameters for analyis. memory should include the estimate for a STAR run.
    memory: 50G
    threads: 1

    # additional fasta file, usually ERCC or other spike in
    extra:

    # path to singularity container.
    singularity: path/to/singularity/IRFinder

    # path to directory with STAR index
    star: /path/to/REF/STAR/directory.dir

    # path to bed to exclude 
    bed: /path/to/REF/extra-input-files/Human_hg38_nonPolyA_ROI.bed

    # model, contrast, reference group and comparator group. Model must include the term 'IRFinder'
    model: ~group+group:IRFinder
    contrast: group
    reference: CTR
    comparator: MUT

    #number of permutation (default: 0)
    permute: 0

    ################################################################
    #
    # sphinxreport build options
    #
    ################################################################
report:

    # prefix to use for publishing the report from this pipeline
    prefix: default

