#!/usr/bin/env bash

# The expected output is a new conda env file merging all conda packages for production pipelines

# Global variables

SCRIPT_NAME="$0"
SCRIPT_OPTS="$@"
SCRIPT_FOLDER=$(dirname $0)
REPO_FOLDER=$(dirname ${SCRIPT_FOLDER})


## auxiliary functions

# function to report issues and exit
report_problem() {
   echo
   echo $1
   echo
   echo " Aborting. "
   exit 1
}


# function to get the relevant package names and versions
process_env_file() {
   egrep -v '^name|^channels|bioconda|conda-forge|defaults|^dependencies|pip|bx-python|#|^prefix|^ ' $1
}


# function to display help message
help_message() {
   echo
   echo " Takes as input all conda env files for production pipelines on this repo."
   echo
   echo " The output is a new conda env file merging all conda packages for production pipelines."
   echo
   echo " ./merge_conda_deps.sh "
   echo
   exit 1
}


## the script starts here

if [[ $# -ne 0 ]] ; then

   help_message

fi

TMP_OUTPUT=$(mktemp)

for env in `ls ${REPO_FOLDER}/conda/environments/pipeline-*-template.yml`
do

   process_env_file ${env} >> ${TMP_OUTPUT}

done

echo
echo "# output generated by ${SCRIPT_NAME} ${SCRIPT_OPTS}"
echo "# on `date`"
echo
echo "name: cgat-f"
echo
echo "channels:"
echo "- bioconda"
echo "- conda-forge"
echo "- defaults"
echo
echo "dependencies:"

sort -u ${TMP_OUTPUT}

