################################################################
#
#
# Pipeline pipeline_bamstats.py configuration file for sphinxreport
#
# This pipeline.ini file lists some configuration options that you might 
# want a user to set automatically.
#
# Add pipeline specific options into separate sections
#
################################################################
## general options
################################################################


# genome is ucsc convention (e.g. hg38)
genome: hg38

# directory where exported data is located
exportdir: export

# location of indexed genome, needs to be set
genome_dir: /ifs/mirror/genomes/index

# scratchdir for data not to be backed up
scratchdir: /tmp

# a version string
version: ''

# directory for publishing results on the web
web_dir: ../web

# Memory allocated for Picard tools (must be nG, number followed by G)
picard_memory: 12G

################################################################
## bam file parameters
################################################################
bam:

    paired_end: 0

    # sometimes a bam has its sequence quality stripped to save space
    # if this is the case then specify below:
    sequence_stripped: 0

    ################################################################
    ## name of the database that you want to generate
    ################################################################
database:

    url: sqlite:///./csvdb

    ################################################################
    ## Location of pipeline_genesets database 
    ################################################################
gtf:

    #database location 
    database: /path/to/dir

    # location that pipeline_genesets.py was ran in
    dir: /path/to/dir


